# mysql connect configuration
jwt:
  signingkey: 'homestyle'
  expirestime: 604800
  buffertime: 86400
mysql:
  name: "homestyle"
  host: "127.0.0.1:3306"
  username: "root"
  password: "123456"
addr: 8866