# mysql connect configuration
jwt:
  signingkey: 'homestyle'
  expirestime: 604800
  buffertime: 86400
mysql:
  name: "homestyle"
  host: "127.0.0.1:3306"
  username: "root"
  password: "123456"
juhe:
  juheurl: "http://v.juhe.cn/sms/send"
  apikey: "6372a0a15446a67e2576d538f02f55b5"
  tplid: 185962
  tplvalue: "#code#=185962"
zap:
  level: 'info'
  format: 'json'
  director: './logs'
  linkname: 'latest_log'
  showline: true
  encodelevel: 'LowercaseColorLevelEncoder'
  stacktracekey: 'stacktrace'
  loginconsole: true
oss:
  accesskeyid: 'LTAI4FwqokDreZU6t3q7hzqP'
  accesskeysecret: 'qA90MM4eNhcqZAiIbcstuFlKbQ0TfA'
  endpoint: 'oss-cn-beijing.aliyuncs.com'
  bucket: 'homestyle'
  uploaddir: 'home'
  ossserve: 'https://homestyle.oss-cn-beijing.aliyuncs.com/'
header: 'http://qqbi9utzj.hd-bkt.clouddn.com/Fhh6BiidOhTl-a86HdU2fozVI8BI'
addr: 8866